server:
  port: 10002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared/ # 搜索src/main/resource 下的properties文件夹下的文件
  application:
    name: spring-eos-eureka-config
  profiles:
    active: native  # 配置使用本地储存
security:
  user:
    password: eos
logging:
      file: ./log/eos-config.log